# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDis.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1265, 619)
        self.rulePushButton = QtWidgets.QPushButton(dialog)
        self.rulePushButton.setGeometry(QtCore.QRect(140, 550, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.rulePushButton.setFont(font)
        self.rulePushButton.setObjectName("rulePushButton")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(150, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(420, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputFactTextEdit = QtWidgets.QTextEdit(dialog)
        self.inputFactTextEdit.setGeometry(QtCore.QRect(410, 60, 151, 371))
        self.inputFactTextEdit.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.inputFactTextEdit.setObjectName("inputFactTextEdit")
        self.inferencePushButton = QtWidgets.QPushButton(dialog)
        self.inferencePushButton.setGeometry(QtCore.QRect(590, 240, 121, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.inferencePushButton.setFont(font)
        self.inferencePushButton.setObjectName("inferencePushButton")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(900, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(550, 470, 171, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ruleTextBrowser = QtWidgets.QTextBrowser(dialog)
        self.ruleTextBrowser.setGeometry(QtCore.QRect(50, 60, 311, 371))
        self.ruleTextBrowser.setObjectName("ruleTextBrowser")
        self.outputTextBrowser = QtWidgets.QTextBrowser(dialog)
        self.outputTextBrowser.setGeometry(QtCore.QRect(730, 60, 511, 371))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.outputTextBrowser.setFont(font)
        self.outputTextBrowser.setObjectName("outputTextBrowser")
        self.answerTextBrowser = QtWidgets.QTextBrowser(dialog)
        self.answerTextBrowser.setGeometry(QtCore.QRect(730, 470, 511, 71))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.answerTextBrowser.setFont(font)
        self.answerTextBrowser.setObjectName("answerTextBrowser")
        self.inputLineEdit = QtWidgets.QTextEdit(dialog)
        self.inputLineEdit.setGeometry(QtCore.QRect(50, 440, 311, 81))
        self.inputLineEdit.setObjectName("inputLineEdit")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "推理机"))
        self.rulePushButton.setText(_translate("dialog", "添加规则"))
        self.label.setText(_translate("dialog", "前提库"))
        self.label_2.setText(_translate("dialog", "输入事实"))
        self.inferencePushButton.setText(_translate("dialog", "进行推理"))
        self.label_3.setText(_translate("dialog", "推理过程"))
        self.label_4.setText(_translate("dialog", "推理结果："))
